FROM ubuntu:20.04

# env
ENV ENV_UID="$ENV_UID"
ENV ENV_UNAME="$ENV_UNAME"
ENV ENV_GID="$ENV_GID"
ENV ENV_GNAME="$ENV_GNAME"
ENV ENV_HOME="$ENV_HOME"
ENV DEBIAN_FRONTEND=noninteractive

# install system env
RUN apt update \
    && apt install -y gosu vim wget rsync

# install aosp env
RUN apt update \
    && apt install -y openjdk-8-jre git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig openssl libssl-dev python python3 python3-pip python3-virtualenv xmlstarlet libtinfo5 uuid-dev python2 libncurses5 libxml-simple-perl python-pillow gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python-yaml uuid-dev \
    && update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

COPY libffi6_3.2.1-8_amd64.deb /tmp/
RUN apt install /tmp/libffi6_3.2.1-8_amd64.deb \
    && rm /tmp/libffi6_3.2.1-8_amd64.deb

RUN mkdir -p /root/bin \
    && echo "#! /bin/bash" > /root/bin/gcc \
    && echo "exec /usr/bin/gcc ${1+\"$@\"} -Wno-error" >> /root/bin/gcc \
    && chmod -R a+rx /root/bin \
    && echo "export PATH=~/bin:\$PATH" >> /etc/profile

# entrypoint
WORKDIR /root/
COPY entry.sh /root/entry.sh
RUN chmod a+x /root/entry.sh
ENTRYPOINT ["/root/entry.sh"]
CMD ["/bin/bash"]

