FROM ubuntu:16.04

# env
ENV ENV_UID="$ENV_UID"
ENV ENV_UNAME="$ENV_UNAME"
ENV ENV_GID="$ENV_GID"
ENV ENV_GNAME="$ENV_GNAME"
ENV ENV_HOME="$ENV_HOME"
ENV DEBIAN_FRONTEND=noninteractive

# install system env
RUN apt-get update \
    && apt-get install -y gosu vim wget rsync

# install aosp env
RUN apt-get update \
    && apt-get install -y openjdk-8-jre git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip openssl libssl-dev python python3 python-pip python3-pip python-virtualenv python3-virtualenv xmlstarlet python-mysqldb python-pillow libxml-simple-perl uuid-dev
 

# entrypoint
WORKDIR /root/
COPY entry.sh /root/entry.sh
RUN chmod a+x /root/entry.sh
ENTRYPOINT ["/root/entry.sh"]
CMD ["/bin/bash"]

